begin
  file = open("/unexistant_file")
  if file
  puts "File opened successfully"
raise 'A test exception.'
rescue => e
puts e.message
end